name: ninjafood
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.18
  intl: 0.17.0
  http: ^0.13.5
  appwrite: ^8.3.0
  fpdart: ^0.5.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5

  ninja_theme:
    git:
      url: https://github.com/quocbao238/ninjafood_theme.git
      ref: devMaster
  firebase_core: ^2.8.0

  #    path: ../NinjaFood_Theme




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
