name: ninjafood
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  fpdart: ^0.2.0
  freezed: ^2.1.0+1
  go_router: ^4.1.1
  json_serializable: ^6.3.1
  shared_preferences: ^2.0.15
  supabase_flutter: ^0.3.3
  uni_links: ^0.5.1
  validators: ^3.0.0
  flutter_riverpod: 2.3.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^2.1.3
  very_good_analysis: ^3.0.1
  build_runner:
  mockito: ^5.2.0
  flutter_gen:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/env/local.config.json
    - assets/env/development.config.json
    - assets/env/production.config.json

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    local:
      app:
        name: "NinjaFood Local"

      android:
        applicationId: "com.rubystdio.ninjafood.local"
      ios:
        bundleId: "com.rubystdio.ninjafood.local"

    development:
      app:
        name: "NinjaFood Development"

      android:
        applicationId: "com.rubystdio.ninjafood.dev"
      ios:
        bundleId: "com.rubystdio.ninjafood.dev"

    production:
      app:
        name: "NinjaFood Production"

      android:
        applicationId: "com.rubystdio.ninjafood"
      ios:
        bundleId: "com.rubystdio.ninjafood"